[functions.ai-question-answer]
verify_jwt = true

[functions.ai-question-answer.env]
# TODO: Replace these with your new API keys
OPENAI_API_KEY = "your-new-openai-api-key"
SUPABASE_URL = "your-supabase-project-url"
SUPABASE_SERVICE_ROLE_KEY = "your-new-supabase-service-role-key" 