version: '3.8'

services:
  energia-ai:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
    env_file:
      - .env
    depends_on:
      - postgres
      - mongodb
      - redis
      - elasticsearch
      - qdrant
    networks:
      - energia-network
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Production database configurations with better security
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: energia_ai
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - energia-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

  # Include other services with production configurations...
  # (Similar to development but with production settings)

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  elasticsearch_data:
  qdrant_data:
  neo4j_data:

networks:
  energia-network:
    driver: bridge
