// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.js';

// IMPORTANT: Environment variables are loaded by the application's entry point.
// For Vitest, this is handled in `src/test/globalSetup.ts`.
// For SvelteKit, this is handled by Vite.
// This client file should NOT load .env files itself to avoid side effects.

const supabaseUrl =
  // Used by Vite/SvelteKit on the client-side
  import.meta.env?.VITE_SUPABASE_URL ??
  // Used in server-side environments (Node.js, tests)
  process.env.VITE_SUPABASE_URL ??
  process.env.SUPABASE_URL;

const supabaseKey =
  // Used by Vite/SvelteKit on the client-side
  import.meta.env?.VITE_SUPABASE_ANON_KEY ??
  // Used in server-side environments (Node.js, tests)
  process.env.VITE_SUPABASE_ANON_KEY ??
  process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  // This error will be thrown if the .env file is missing or the variables are not set.
  // If this happens during a test run, check `src/test/globalSetup.ts`.
  throw new Error('Supabase URL and Anon Key must be defined in the environment variables.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);
