name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-checks:
    name: PR Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff mypy

    - name: Check code formatting
      run: |
        ruff format --check --diff .

    - name: Run linting
      run: |
        ruff check . --output-format=github

    - name: Type checking
      run: |
        mypy src/ --ignore-missing-imports

    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD

  pr-size-check:
    name: PR Size Check
    runs-on: ubuntu-latest
    steps:
    - name: Check PR size
      uses: actions/github-script@v6
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
          });
          
          const additions = pr.additions;
          const deletions = pr.deletions;
          const changes = additions + deletions;
          
          if (changes > 1000) {
            core.setFailed(`PR is too large (${changes} lines changed). Consider breaking it into smaller PRs.`);
          } else if (changes > 500) {
            core.warning(`PR is quite large (${changes} lines changed). Consider reviewing if it can be split.`);
          }
